name: Museum Park Floating Pool
favicon: null
layout_spectrum: 0
typography_spectrum: 0.44493
title: Museum Park Floating Pool
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.0625
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
